Repository near/near-discovery-components, pull requests merged in 2023-11, with the labels that each got.

#470 support auto-generated release notes
  .github/release.yml
  .github/workflows/prs_must_have_labels.yml
Labels: enhancement

#475 feat(AppLibrary.IndexPage) Update fetch
  src/AppLibrary/IndexPage.jsx
Labels: feature

#476 NEAR Org Landing Pages (Part 1 of 2)
  src/NearOrg/BlockchainPage.jsx
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/DataInfrastructurePage.jsx
  src/NearOrg/FastAuthAndRelayersPage.jsx
  src/NearOrg/Footer.jsx
  src/NearOrg/HomePage.jsx
  src/NearOrg/OpenWebApplicationsPage.jsx
Labels: enhancement

#398 Prepare settings page to show identity tab
  src/Settings/Identity/Alert.jsx
  src/Settings/Identity/Banner.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Verifications/Card.jsx
  src/Settings/Identity/Verifications/Index.jsx
  src/Settings/Identity/Verifications/List.jsx
  src/Settings/Index.jsx
  src/Settings/Sidebar.jsx
Labels: feature

#482 Use posts table to determine whether QueryApi matches Social.index.
  src/ActivityFeeds/DetermineActivityFeed.jsx
Labels: bug

#484 Fix several small Moderator interface bugs
  indexers/moderation/moderation.js
  indexers/moderation/moderation.sql
  src/Moderation/Moderator.jsx
  src/Moderation/NeedsModeration.jsx
  src/Moderation/TogglingSetButton.jsx
Labels: bug

#486 Fix alignment of action buttons for NotificationAlert
  src/NearOrg/Notifications/NotificationAlert.jsx
Labels: bug

#480 feature: add leaderboard charts to ncon
  ngrok.yml
  src/AppLibrary/Nearcon/Charts/TopUpvotedApps.jsx
  src/AppLibrary/Nearcon/IndexPage.jsx
  src/AppLibrary/Nearcon/IndexPage.metadata.json
Labels: feature

#487 chore: delete accidentally checked in file
  ngrok.yml
  src/AppLibrary/Nearcon/Charts/TopUpvotedApps.jsx
  src/AppLibrary/Nearcon/IndexPage.jsx
Labels: bug

#488 Add mobile view to the Settings page
  src/Settings/Identity/Verifications/Card.jsx
  src/Settings/Index.jsx
  src/Settings/Sidebar.jsx
Labels: feature

#489 Promote develop -> main
  src/AppLibrary/Nearcon/Charts/TopUpvotedApps.jsx
  src/AppLibrary/Nearcon/IndexPage.jsx
  src/AppLibrary/Nearcon/IndexPage.metadata.json
  src/Settings/Identity/Verifications/Card.jsx
  src/Settings/Index.jsx
  src/Settings/Sidebar.jsx
Labels: ignore-for-release

#491 fix upvote bug
  src/ComponentSummary.jsx
Labels: bug

#499 fix stats for ncon app quest
  src/AppLibrary/Nearcon/IndexPage.jsx
Labels: bug

#504 Fix `Add Credentials` button on settings page
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release

#503 Show data availability link in footer
  src/NearOrg/Footer.jsx
Labels: ignore-for-release

#500 Removes the redirect to a custom ProfilePage component
  src/ProfilePage.jsx
Labels: enhancement

#505 Non-regular promotion develop -> main
  src/AppLibrary/Nearcon/IndexPage.jsx
  src/NearOrg/Footer.jsx
  src/ProfilePage.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release

#508 chore: Update PoP and KYC links
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release

#511 chore: Update PoP and KYC links and promote as hotfix
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release

#516 Check type of accounts_liked data before parsing.
  src/Posts/Post.jsx
Labels: bug

#502 Fix caching issue with component details stats
  src/ComponentProfile.jsx
Labels: bug

#515 Standalone post and comment views incorporate moderation
  src/ActivityFeeds/PostsFeedControls.jsx
  src/Moderation/CheckPostModeration.jsx
  src/Moderation/ModeratedItemMessage.jsx
  src/PostPage.jsx
  src/Posts/ModeratedPostData.jsx
Labels: feature

#501 fix release.yml formatting, with unicode for the emojis
  .github/release.yml
Labels: ignore-for-release

#518 Apply hotfix: Check type of accounts_liked data before parsing.
  src/Posts/Post.jsx
Labels: ignore-for-release

#521 Added handleCloseSearchMenu to close search UI
  src/Search/TypeAheadDropdown.jsx
Labels: bug

#530 fix: Rendering post for accounts with no seft moderated data
  src/Moderation/CheckPostModeration.jsx
Labels: bug

#531 Weekly promotion of develop to main - early release
  src/AccountProfileOverlay.jsx
  src/DIG/Button.jsx
  src/DIG/Dialog.jsx
  src/Flagged/Modal.jsx
  src/Moderation/CheckPostModeration.jsx
  src/NearOrg/Ecosystem/CommunityPage.jsx
  src/NearOrg/Ecosystem/GetFundingPage.jsx
  src/NearOrg/Ecosystem/OverviewPage.jsx
  src/NearOrg/Ecosystem/WorkAndEarnPage.jsx
  src/Search/Facets.jsx
  src/Search/TypeAheadDropdown.jsx
Labels: ignore-for-release

#520 Added block menu in notification list
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
Labels: feature

#533 Align the notification mention UI #533
  src/NearOrg/Notifications/CommentContent.jsx
  src/NearOrg/Notifications/CommentPost.jsx
  src/NearOrg/Notifications/Notification.jsx
Labels: enhancement

#538 refactor: Connect to idOS on page load
  src/Settings/Identity/Banner.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Verifications/Index.jsx
Labels: enhancement, refactor

#540 fix: Fix link to DevHub posts on notifications page
  src/NearOrg/Notifications/Notification.jsx
Labels: enhancement

#541 Fix for adding a comments
  src/Comments/Comment.jsx
  src/Posts/Post.jsx
Labels: bug

#546 develop -> main
  src/Comments/Comment.jsx
  src/ExploreWidgets.jsx
  src/NearOrg/Notifications/Notification.jsx
  src/News/NearweekSidebarFeed.jsx
  src/Posts/Post.jsx
  src/Settings/Identity/Banner.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release
