Repository near/near-discovery-components, pull requests merged in 2023-12, with the labels that each got.

#548 Refactor `ComponentDetailsPage`
  src/ComponentDetails/Content.jsx
  src/ComponentDetails/Sidebar.jsx
  src/ComponentDetailsPage.jsx
Labels: enhancement

#542 Add content preview in notifications
  src/NearOrg/Notifications/Banner.jsx
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/SettingsListItem.jsx
Labels: enhancement

#554 feat: optimistic update for post
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ComponentDetails/Content.jsx
  src/ComponentDetails/Sidebar.jsx
  src/Onboarding/ComponentCollection.jsx
  src/Posts/Compose.jsx
  src/Posts/Post.jsx
Labels: feature

#558 Fix: Improve and align notification UI components
  src/Comments/Comment.jsx
  src/NearOrg/Notifications/CommentContent.jsx
  src/NearOrg/Notifications/CommentPost.jsx
  src/Posts/Post.jsx
Labels: bug

#544 Update devhub notification post redirect from 'devgovgigs' to 'devhub' account widgets
  src/NearOrg/Notifications/Notification.jsx
Labels: bug

#550 Contribution Graph
  src/DeveloperProfile/ContributionGraph.jsx
Labels: feature

#560 Typo fix
  src/NearOrg/HomePage.jsx
  src/NearOrg/Notifications/SettingsListItem.jsx
Labels: ignore-for-release

#549 refactor: Limit number of indexed Post in nearWeekNews
  src/News/NearweekSidebarFeed.jsx
Labels: enhancement

#562 chore: add brandtoolkit to footer
  src/NearOrg/Footer.jsx
Labels: enhancement

#565 fix: remove explore tab from profile page
  src/ProfilePage.jsx
Labels: bug

#563 feat: Add click directly on TabsButton
  src/ActivityPage.jsx
Labels: bug

#568 fix: Remove Flag button from Posts and Comments
  src/Comments/Comment.jsx
  src/Posts/Post.jsx
Labels: bug

#559 feat: Update auto complete widget
  src/AccountAutocomplete.jsx
Labels: enhancement

#566 chore: add environment deployment details
  README.md
Labels: documentation, enhancement

#571 fix: resolve duplicate declaration merge error
  src/Settings/Identity/Verifications/Index.jsx
Labels: ignore-for-release

#574 Fix: Improved three dots placement in CommentPost component
  src/NearOrg/Notifications/CommentPost.jsx
Labels: bug

#576 feat: components indexer
  indexers/components/components.js
  indexers/components/components.sql
Labels: enhancement

#567 feat: create CookieDetails component
  src/NearOrg/CookieDetails.jsx
  src/NearOrg/CookiePolicy.jsx
Labels: enhancement

#578 887 data availability comparison chart
  src/AccountAutocomplete.jsx
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#581 887 da comparison chart
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#582 NEAR-448 FIX: Updated z-index for Radix Popover due to underlying UI issues
  src/DIG/DropdownMenu.jsx
Labels: bug

#577 feat: update unseen posts every 5s
  src/ActivityFeeds/DetermineActivityFeed.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ActivityPage.jsx
Labels: feature

#583 fix code widget on testnet
  replacements.dev.json
  replacements.mainnet.json
  replacements.testnet.json
  src/ComponentHistory.jsx
  src/NearOrg/CookiePolicy.jsx
Labels: bug

#585 NEAR-879 FIX: Updated z-index for profile overlay issue
  src/AccountProfileOverlay.jsx
  src/Posts/Post.jsx
Labels: bug

#589 fix copy pasta
  replacements.mainnet.json
Labels: ignore-for-release
