Repository near/near-discovery-components, pull requests merged in 2024-02, with the labels that each got.

#633 fix: add a `tags` field to accounts indexer schema
  indexers/accounts/accounts.sql
Labels: enhancement

#635 style: partner logo and copy updates
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/Ecosystem/OverviewPage.jsx
  src/NearOrg/HomePage.jsx
Labels: enhancement

#640 fix: trusted partners display should flex to mobile screens
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/HomePage.jsx
Labels: enhancement

#641 hotfix: trusted partners display should flex to mobile screens (#640)
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/HomePage.jsx
Labels: ignore-for-release

#636 fix: Update UI when a new comment is added
  src/Comments/Compose.jsx
  src/Posts/Post.jsx
Labels: bug

#644 feat: an EntityList with example usage
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntityPage.jsx
Labels: feature

#634 feat: use accounts indexer for posts feed
  indexers/feed/relationships.json
  src/AccountProfile.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/Posts/Feed.jsx
Labels: enhancement

#645 chore: update DA page
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#646 non-regular promotion develop -> main
  indexers/feed/relationships.json
  src/AccountProfile.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/Comments/Compose.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntityPage.jsx
  src/NearOrg/DataAvailabilityPage.jsx
  src/Posts/Feed.jsx
  src/Posts/Post.jsx
Labels: ignore-for-release

#647 feat: initial agent framework
  indexers/agents/agents.js
  indexers/agents/agents.sql
  src/Entities/AgentFramework/AgentCard.jsx
  src/Entities/AgentFramework/AgentChat.jsx
  src/Entities/AgentFramework/AgentCreate.jsx
  src/Entities/AgentFramework/AgentHeader.jsx
  src/Entities/AgentFramework/AgentPage.jsx
  src/Entities/Template/EntityList.jsx
Labels: feature

#648 feat: create a new component for `papers` page
  src/NearOrg/PapersPage.jsx
Labels: enhancement

#651 fix: notification prompt message
  src/NearOrg/Notifications/Banner.jsx
  src/NearOrg/Notifications/Notifications.jsx
Labels: enhancement

#653 ecosystem overview, funding and support content updates
  .github/workflows/release_notes.yml
  src/NearOrg/Ecosystem/GetFundingPage.jsx
  src/NearOrg/Ecosystem/OverviewPage.jsx
  src/NearOrg/EcosystemPage.jsx
  src/NearOrg/LearnPage.jsx
Labels: enhancement

#655 Add Brazil Hub and alphabetize hubs
  src/NearOrg/Ecosystem/GetFundingPage.jsx
Labels: enhancement

#654 mvp of rebuilding near.org/blog as BOS components
  src/Blog/Feed.jsx
Labels: feature

#656 feat: simplifying the action buttons on the component details card
  src/ComponentSummary.jsx
Labels: enhancement

#658 fix: minor copy update
  src/NearOrg/FoundersPage.jsx
Labels: ignore-for-release

#659 develop -> main
  src/ComponentSummary.jsx
  src/NearOrg/FoundersPage.jsx
Labels: ignore-for-release

#661 Move to AI Folder
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentCreate.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentHeader.jsx
  src/AI/Agent/AgentSummary.jsx
  src/AI/Nexus.jsx
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
  src/Entities/Template/EntityList.jsx
Labels: refactor

#662 feat: agentchat supports multiple providers
  src/AI/Agent/AgentChat.jsx
  src/DIG/InputSelect.jsx
Labels: feature

#665 fix: incorrect component paths
  src/AI/Agent/AgentChat.jsx
Labels: ignore-for-release

#667 fix merge
  src/AI/Agent/AgentChat.jsx
Labels: ignore-for-release

#668 Custom chat component
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentCreate.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentSummary.jsx
Labels: feature

#669 Custom chat component (#668)
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentCreate.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentSummary.jsx
Labels: ignore-for-release

#671 Updated copy for ecosystem funding outlets and community groups
  src/NearOrg/Ecosystem/GetFundingPage.jsx
  src/NearOrg/FoundersPage.jsx
Labels: enhancement

#670 chore: add token checklist file to the founders page
  src/NearOrg/FoundersPage.jsx
Labels: enhancement

#672 fix: leverage REPL account injection
  src/NearOrg/CookieDetails.jsx
Labels: ignore-for-release

#674 feature the new nearweek new app
  .github/workflows/promote-develop-to-main.yml
  src/NearOrg/Footer.jsx
  src/NearOrg/HomePage.jsx
  src/News/NearweekSidebarFeed.jsx
Labels: feature

#675 develop -> main
  .github/workflows/promote-develop-to-main.yml
  src/DIG/Dialog.jsx
  src/NearOrg/CookieDetails.jsx
  src/NearOrg/CookiePolicy.jsx
  src/NearOrg/CookiePrompt.jsx
  src/NearOrg/Ecosystem/GetFundingPage.jsx
  src/NearOrg/Footer.jsx
  src/NearOrg/FoundersPage.jsx
  src/NearOrg/HomePage.jsx
  src/News/NearweekSidebarFeed.jsx
Labels: ignore-for-release

#676 chore: update text on founters page
  src/NearOrg/FoundersPage.jsx
Labels: enhancement

#677 non-regular promotion develop -> main
  .github/workflows/release_notes.yml
  src/NearOrg/FoundersPage.jsx
Labels: ignore-for-release

#678 avoid overwriting notes when creating > 1 release per day
  .github/workflows/release_notes.yml
Labels: ignore-for-release
