Repository near/near-discovery-components, pull requests merged in 2024-04, with the labels that each got.

#736 Entity delete
  indexers/entities/entities.js
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: feature

#737 chore: add hover effects on gatewat home page
  src/Gateway/Home.jsx
Labels: enhancement

#739 fix: add overflow to username on notifications
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: enhancement

#734 feat: write only latest entity change, misc
  indexers/components/components.js
  indexers/entities/entities.js
  src/Entities/Examples/FavoriteCars.jsx
  src/Entities/Examples/FavoritePlaces.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: enhancement

#740 Daily release
  indexers/components/components.js
  indexers/entities/entities.js
  src/Entities/Examples/FavoriteCars.jsx
  src/Entities/Examples/FavoritePlaces.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Gateway/Home.jsx
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: ignore-for-release

#742 enhancement: Update data availability copy
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#744 Data availability copy edit
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#743 Pinned Apps (1 of 2)
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentSummary.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ComponentDetailsPage.jsx
  src/ComponentSummary.jsx
  src/GatewayWrapper.jsx
  src/Moderation/ModerationButton.jsx
  src/Moderation/Moderator.jsx
  src/Moderation/NeedsModeration.jsx
  src/Moderation/ReasonDialog.jsx
  src/ProfilePage.jsx
  src/SocialIndexActionButton.jsx
Labels: feature

#749 Production Deployment
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentSummary.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ComponentDetailsPage.jsx
  src/ComponentSummary.jsx
  src/GatewayWrapper.jsx
  src/Moderation/ModerationButton.jsx
  src/Moderation/Moderator.jsx
  src/Moderation/NeedsModeration.jsx
  src/Moderation/ReasonDialog.jsx
  src/NearOrg/DataAvailabilityPage.jsx
  src/ProfilePage.jsx
  src/SocialIndexActionButton.jsx
Labels: ignore-for-release

#747 Home update
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/HomePage.jsx
Labels: ignore-for-release

#752 fix: prevent notification fallback logic from being stuck
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
Labels: enhancement

#741 fix: check data format
  indexers/components/components.js
  indexers/feed/relationships.json
Labels: bug

#754 Daily release
  indexers/components/components.js
  indexers/feed/relationships.json
  src/Entities/Template/EntityDetails.jsx
Labels: ignore-for-release

#755 Clear ai folder
  indexers/agents/agents.js
  indexers/agents/agents.sql
  src/AI/Agent/AgentCard.jsx
  src/AI/Agent/AgentChat.jsx
  src/AI/Agent/AgentCreate.jsx
  src/AI/Agent/AgentDetails.jsx
  src/AI/Agent/AgentHeader.jsx
  src/AI/Agent/AgentSummary.jsx
  src/AI/DO_NOT_USE.md
  src/AI/Nexus.jsx
Labels: ignore-for-release

#756 fix: notification counter
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
Labels: enhancement

#758 feat: add meta tag feature to blogpost pages
  src/BlogPostPage.jsx
Labels: enhancement

#760 Contact Us Page (1 of 2)
  src/Gateway/ContactUsPage.jsx
Labels: feature

#762 Add warpcast link to contact us page
  src/Gateway/ContactUsPage.jsx
Labels: ignore-for-release

#763 exit early from the render function until the fetchGraphQL module loads
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
Labels: bug

#759 fix: entities indexer handles empty namespace key
  indexers/entities/entities.js
  indexers/entities/entities_tests.js
  indexers/entities/test_block.js
Labels: bug

#765 Populate edit view with attributes
  src/Entities/Template/EntityCreate.jsx
Labels: bug

#767 Entity home link
  src/Entities/Examples/FavoriteCarSchema.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: feature

#769 chore: get rid of some simple errors
  src/ComponentCard.jsx
  src/ComponentSummary.jsx
  src/NearOrg/CookiePrompt.jsx
  src/News/NearweekSidebarFeed.jsx
Labels: ignore-for-release

#771 Ensure the Create Account CTAs trigger the auth modals
  src/NearOrg/BlockchainPage.jsx
  src/NearOrg/HomePage.jsx
Labels: bug

#772 deploy a fix to the Create Account CTA
  src/ComponentCard.jsx
  src/ComponentSummary.jsx
  src/NearOrg/BlockchainPage.jsx
  src/NearOrg/CookiePrompt.jsx
  src/NearOrg/HomePage.jsx
  src/News/NearweekSidebarFeed.jsx
Labels: ignore-for-release

#773 fix: star count, additional tabs on detail
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: bug

#776 Revert da copy
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#777 feat: entity list can be filtered by tags
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/Forms/TagsEditor.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: feature

#778 feat: support global tag filtering for entities
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/Forms/TagCloud.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Moderation/Sidebar.jsx
Labels: feature

#779 non-regular promotion develop -> main
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/Forms/TagCloud.jsx
  src/Entities/Template/Forms/TagsEditor.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Moderation/Sidebar.jsx
  src/NearOrg/DataAvailabilityPage.jsx
Labels: ignore-for-release

#774 feat: core indexer status component auto-updates, removed old column
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: enhancement

#780 fix: global tag filter uses properties instead of Storage
  src/DIG/Tabs.jsx
  src/DIG/Tabs.metadata.json
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/Forms/TagCloud.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: bug

#782 Release tag fix
  src/DIG/Tabs.jsx
  src/DIG/Tabs.metadata.json
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/Forms/TagCloud.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: ignore-for-release

#785 feat: the Indexer status page uses new QueryApi status tables
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
  src/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: enhancement

#783 chore: cleanup of Post related components
  src/ActivityFeeds/DetermineActivityFeed.jsx
  src/ActivityFeeds/PostsFeedControls.jsx
  src/NearOrg/DataAvailabilityPage.jsx
  src/v1/Feed.jsx
  src/v1/Posts.jsx
  src/v1/Posts/Feed.jsx
Labels: ignore-for-release

#791 Entity file upload
  src/Entities/QueryApi/Ipfs.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/Forms/FormBuilder.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Entities/Template/GenericSchema.jsx
Labels: feature
