Repository near/near-discovery-components, pull requests merged in 2024-01, with the labels that each got.

#586 feat: add accounts indexer
  indexers/accounts/accounts.js
  indexers/accounts/accounts.sql
Labels: feature

#569 Refactor NearOrg/Notifications components
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: enhancement

#592 chore: add /privacy and /terms links into the footer
  src/NearOrg/Footer.jsx
Labels: enhancement

#579 Metadata in components indexer
  indexers/components/components.js
  indexers/components/components.sql
Labels: enhancement

#594 Safer JSON.parse() in components indexer
  indexers/components/components.js
Labels: enhancement

#598 fix: Replaced a with Link to prevent unnecessary page reloads on profile
  src/AccountProfile.jsx
  src/Recommender/Account/AccountProfileSidebar.jsx
Labels: bug

#604 feat: display QueryApi indexer statuses for a given user
  src/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: feature

#601 fix: update data availability partner links
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#597 fix: fixed styling bugs in profile editor view
  src/ProfilePage.jsx
Labels: bug

#602 Adding contribution graph to profile page
  src/ProfilePage.jsx
Labels: feature

#599 Refactor AccountProfile component
  src/AccountProfile.jsx
Labels: enhancement

#605 Enable sending notifications for interactions on comment
  src/Comments/Comment.jsx
  src/v1/LikeButton.jsx
Labels: enhancement

#608 feat: implement verification icons component
  src/AccountProfileOverlay.jsx
  src/Settings/Identity/Verifications/Icon.jsx
Labels: enhancement

#606 Show verified user badges on profile
  src/AccountProfile.jsx
  src/AccountProfileOverlay.jsx
  src/ProfilePage/ProfileBadges.jsx
  src/ProfilePage/Sidebar.jsx
  src/Recommender/Account/AccountProfileSidebar.jsx
Labels: feature

#611 fix: exception stack trace on opening the notifications overlay
  src/NearOrg/Notifications/Notification.jsx
Labels: enhancement

#587 fix: fully check data field in indexers
  indexers/moderation/moderation.js
  indexers/social_feed/social_feed.js
  indexers/verifications/verifications.js
Labels: bug

#613 fix: Added handleCloseSearchMenu to close the search bar
  src/Search/TypeAheadDropdown.jsx
Labels: bug

#607 feat: idOS design enhancement
  src/Settings/Identity/Banner.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Onboarding/Cards.jsx
  src/Settings/Identity/Verifications/Index.jsx
  src/Settings/Identity/Verifications/List.jsx
Labels: enhancement

#616 chore: temp partner removal
  src/NearOrg/DataAvailabilityPage.jsx
Labels: ignore-for-release

#615 develop -> main
  indexers/moderation/moderation.js
  indexers/social_feed/social_feed.js
  indexers/verifications/verifications.js
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/Notifications/Notification.jsx
  src/ProfileEditor.jsx
  src/ProfilePage.jsx
  src/Search/TypeAheadDropdown.jsx
  src/Settings/Identity/Banner.jsx
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Onboarding/Cards.jsx
  src/Settings/Identity/Verifications/Index.jsx
  src/Settings/Identity/Verifications/List.jsx
Labels: ignore-for-release

#617 fix: Fixed notification long horizontal content
  src/NearOrg/Notifications/Notification.jsx
Labels: bug

#621 feat: created a new table and updated indexer to capture stars/fork f…
  indexers/components/components.js
Labels: ignore-for-release

#618 Moderators can specify the reason for moderation
  src/Moderation/ModerationButton.jsx
  src/Moderation/Moderator.jsx
  src/Moderation/NeedsModeration.jsx
  src/Moderation/ReasonDialog.jsx
  src/Moderation/TogglingSetButton.jsx
Labels: feature

#623 Users choose a reason when reporting content
  src/Posts/Menu.jsx
Labels: feature

#619 feat: updated components.sql to capture stars/forks and additional info
  indexers/components/components.js
  indexers/components/components.sql
Labels: feature

#629 chore: include cookie policy in the footer
  src/NearOrg/Footer.jsx
Labels: documentation

#627 fix: fixed view notification button preview for like type notification
  src/NearOrg/Notifications/utils.jsx
Labels: bug

#628 feat: add polygon logo, move arbitrum, update logo sizes
  src/NearOrg/DataAvailabilityPage.jsx
Labels: enhancement

#624 fix: correct reporter count & list on needs moderation page
  indexers/moderation/moderation.sql
  src/Moderation/NeedsModeration.jsx
Labels: bug

#630 feat: moved moderated_posts and moderated_comments views to feed inde…
  indexers/feed/README.md
  indexers/feed/feed.js
  indexers/feed/feed.sql
  indexers/feed/relationships.json
  indexers/social_feed/social_feed.sql
  src/ActivityFeeds/PostsFeedControls.jsx
  src/Posts/ModeratedPostData.jsx
Labels: enhancement

#631 fix: fixed notification content description
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: bug
