Repository near/near-discovery-components, pull requests merged in 2024-03, with the labels that each got.

#680 feat: create an events page component
  src/Events/Card.jsx
  src/Events/CardLarge.jsx
  src/Events/Index.jsx
Labels: enhancement

#622 feature : Adding from followed in components discovery
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ActivityFeeds/test.js
  src/ComponentCard.jsx
  src/ComponentDetailsPage.jsx
  src/FeaturedComponents.jsx
Labels: enhancement

#684 develop -> main
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ActivityFeeds/test.js
  src/ComponentCard.jsx
  src/ComponentDetailsPage.jsx
  src/Events/Card.jsx
  src/Events/CardLarge.jsx
  src/Events/Index.jsx
  src/FeaturedComponents.jsx
Labels: ignore-for-release

#673 enhancement: add prompt to signin/signup for users taking actions on blog posts
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
  src/CommentButton.jsx
  src/Posts/Post.jsx
  src/v1/LikeButton.jsx
Labels: enhancement

#683 fix: timeAgo needs a REPL reference to the component's blockheight
  src/NearOrg/Notifications/Notification.jsx
  src/Search/FullPage/ComponentCard.jsx
  src/Search/FullPage/PostCard.jsx
Labels: bug

#682 sign-in now uses the new fastauth modal overlayed on top of the current page or the applications page
  replacements.dev.json
  replacements.mainnet.json
  replacements.testnet.json
  src/ActivityFeeds/PostsFeedControls.jsx
  src/ComponentCard.jsx
  src/ComponentDetailsPage.jsx
  src/FeaturedComponents.jsx
  src/NearOrg/BlockchainPage.jsx
  src/NearOrg/HomePage.jsx
  src/Settings/Identity/Onboarding/Cards.jsx
Labels: feature

#687 only Required cookies were enabled for all users due to error in passing boolean values
  src/NearOrg/CookiePrompt.jsx
Labels: bug

#686 chore: add placeholders to events page
  src/Events/Index.jsx
Labels: enhancement

#689 chore: style improvements of founders page
  src/NearOrg/FoundersPage.jsx
Labels: enhancement

#691 fix: better validation for create or edit agents
  src/AI/Agent/AgentCreate.jsx
  src/AI/Agent/AgentHeader.jsx
Labels: bug

#694 feat: entity create
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntityPage.jsx
Labels: feature

#696 Off cycle release
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntityPage.jsx
  src/NearOrg/DataAvailabilityPage.jsx
  src/NearOrg/FoundersPage.jsx
Labels: ignore-for-release

#697 Restyle blog to adhere to figma design
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
Labels: enhancement

#698 chore: repl_devhub
  replacements.dev.json
  replacements.mainnet.json
  replacements.testnet.json
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityList.jsx
Labels: ignore-for-release

#699 Make changes to handle new signup flow + comments
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
  src/LikeButton.jsx
  src/Posts/Post.jsx
  src/v1/LikeButton.jsx
Labels: enhancement

#700 Tab state with sidebar
  src/Moderation/Moderator.jsx
  src/Moderation/NeedsModeration.jsx
Labels: bug

#702 fix: force initial string values in form configurator
  src/Entities/Template/EntityCreate.jsx
Labels: bug

#703 chore: bump actions/checkout to v4 to avoid deprecated node version
  .github/workflows/deploy-dev-testnet.yml
  .github/workflows/deploy-prod-mainnet.yml
  .github/workflows/deploy-prod-testnet.yml
  .github/workflows/promote-develop-to-main.yml
  .github/workflows/release_notes.yml
Labels: dependency

#705 promote ecosystem update
  .github/workflows/deploy-dev-testnet.yml
  .github/workflows/deploy-prod-mainnet.yml
  .github/workflows/deploy-prod-testnet.yml
  .github/workflows/promote-develop-to-main.yml
  .github/workflows/release_notes.yml
  src/NearOrg/Ecosystem/GetFundingPage.jsx
Labels: ignore-for-release

#642 feat: use `accounts` indexer for notifications
  indexers/notifications/notifications.js
  indexers/notifications/notifications.sql
  indexers/notifications/relationships.json
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
Labels: enhancement

#707 Entity details
  indexers/agents/agents.js
  indexers/agents/agents.sql
  src/AI/Agent/AgentCreate.jsx
  src/AI/Nexus.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Entities/Template/GenericSchema.jsx
Labels: feature

#708 fix: corrected REPL_ in entity framework
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: bug

#711 chore: refactor `NotificationButton`
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
  src/NearOrg/Notifications/Preview.jsx
Labels: enhancement

#709 Off cycle release of entity components and notifications
  indexers/agents/agents.js
  indexers/agents/agents.sql
  indexers/notifications/notifications.js
  indexers/notifications/notifications.sql
  indexers/notifications/relationships.json
  src/AI/Agent/AgentCreate.jsx
  src/AI/Nexus.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Entities/Template/GenericSchema.jsx
  src/NearOrg/Notifications/NotificationButton.jsx
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/NotificationsList.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
  src/NearOrg/Notifications/Preview.jsx
Labels: ignore-for-release

#706 feat: implement navbar ui elements
  src/DIG/Input.jsx
  src/Navigation/LargeScreenHeader.jsx
  src/Navigation/ProfileDropdown.jsx
  src/Navigation/Search.jsx
  src/Navigation/SmallScreenHeader.jsx
Labels: enhancement

#712 Sync new navigation components to production
  src/DIG/Input.jsx
  src/Navigation/LargeScreenHeader.jsx
  src/Navigation/ProfileDropdown.jsx
  src/Navigation/Search.jsx
  src/Navigation/SmallScreenHeader.jsx
Labels: ignore-for-release

#692 Added devhub proposal notification
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: enhancement

#715 chore: explore all teams should open in a new tab
  src/NearOrg/Ecosystem/GetFundingPage.jsx
Labels: ignore-for-release

#719 Container Refactor
  src/ActivityPage.jsx
  src/ComponentDetailsPage.jsx
  src/ComponentsPage.jsx
  src/Entities/Template/EntityList.jsx
  src/NearOrg/CookiePrompt.jsx
  src/NearOrg/Ecosystem/CommunityPage.jsx
  src/NearOrg/Ecosystem/GetFundingPage.jsx
  src/NearOrg/Ecosystem/OverviewPage.jsx
  src/NearOrg/Ecosystem/WorkAndEarnPage.jsx
  src/NearOrg/Notifications/Notifications.jsx
  src/NearOrg/Notifications/Settings.jsx
  src/NearOrg/PrivacyPage.jsx
  src/NearOrg/TermsPage.jsx
  src/NearOrg/UsePage.jsx
  src/PeoplePage.jsx
  src/Settings/Index.jsx
Labels: refactor

#720 feat: implement new homepage for logged in users
  src/Gateway/Home.jsx
Labels: enhancement

#721 chore: update marketing dao logo
  src/NearOrg/Ecosystem/GetFundingPage.jsx
Labels: enhancement

#723 Sync Home Page Events (2/2)
  src/NearOrg/HomePage.jsx
  src/NearOrg/LatestEvents.jsx
Labels: enhancement

#729 Fix: Container for Profile and Post Pages
  src/PostPage.jsx
  src/ProfileEditor.jsx
  src/ProfilePage.jsx
Labels: enhancement

#724 fix: broken devhub notifications
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
  src/NearOrg/Notifications/utils.jsx
Labels: enhancement

#731 feat: entity sort and search
  src/Entities/Examples/ComponentsPage.jsx
  src/Entities/Examples/FavoriteCars.jsx
  src/Entities/Examples/FavoritePlaces.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: feature

#732 End of week release
  indexers/agents/agents.js
  indexers/entities/entities.js
  indexers/entities/entities.sql
  src/Entities/Examples/ComponentSchema.jsx
  src/Entities/Examples/ComponentsPage.jsx
  src/Entities/Examples/FavoriteCarSchema.jsx
  src/Entities/Examples/FavoriteCars.jsx
  src/Entities/Examples/FavoritePlaces.jsx
  src/Entities/Template/EntityCreate.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/EntityPage.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/NearOrg/Notifications/Notification.jsx
  src/NearOrg/Notifications/NotificationsMiddleware.jsx
  src/NearOrg/Notifications/utils.jsx
  src/PostPage.jsx
  src/ProfileEditor.jsx
  src/ProfilePage.jsx
Labels: ignore-for-release

#704 feat: add promote menu option, write addToBlog to socialDb
  indexers/social_feed/social_feed.js
  indexers/social_feed/social_feed.sql
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
  src/Posts/Feed.jsx
  src/Posts/Menu.jsx
  src/Posts/Post.jsx
  src/ProfilePage.jsx
  src/v1/Posts/Post.jsx
Labels: feature

#733 Release blog feature
  indexers/social_feed/social_feed.js
  indexers/social_feed/social_feed.sql
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
  src/Posts/Feed.jsx
  src/Posts/Menu.jsx
  src/Posts/Post.jsx
  src/ProfilePage.jsx
  src/v1/Posts/Post.jsx
Labels: ignore-for-release
