Repository near/near-discovery-components, pull requests merged in 2024-05, with the labels that each got.

#796 AI Mobile Part (1 of 2)
  src/DIG/Input.jsx
  src/DIG/Tabs.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Gateway/Home.jsx
  src/Select.jsx
Labels: enhancement

#795 feat: status component includes latest optimistic and final blocks
  src/Entities/QueryApi/Client.jsx
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: enhancement

#787 chore: cleanup old folder
  src/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: ignore-for-release

#797 Release mobile upgrades to Entity Framework
  src/DIG/Input.jsx
  src/DIG/Tabs.jsx
  src/Entities/QueryApi/Client.jsx
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/GenericEntityConfig.jsx
  src/Gateway/Home.jsx
  src/QueryApi/DataPlatformIndexerStatuses.jsx
  src/Select.jsx
Labels: ignore-for-release

#799 feat: toggle image input between url and file upload
  src/Entities/QueryApi/Ipfs.jsx
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntityList.jsx
  src/Entities/Template/Forms/FormBuilder.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: feature

#800 Add builder perks content
  src/NearOrg/FoundersPage.jsx
Labels: enhancement

#801 chore: use `gap` as it was before
  src/Gateway/Home.jsx
Labels: ignore-for-release

#802 chore: update the homepage to feature fullstack development resources
  src/Gateway/Home.jsx
Labels: enhancement

#804 fix: static Flex style to prevent search render interactions
  src/Entities/Template/EntityList.jsx
Labels: bug

#805 fix: clean up
  src/Entities/Template/EntityDetails.jsx
  src/Entities/Template/EntitySummary.jsx
  src/Entities/Template/GenericEntityConfig.jsx
Labels: bug

#808 Conditionally render NearOrg.Footer on BlogPostPage (1 of 2)
  src/BlogPostPage.jsx
Labels: bug

#812 fix: create blogComponentUrl as props to passed to the blog widget
  src/Blog/Feed.jsx
  src/BlogPostPage.jsx
Labels: enhancement

#810 fix: handle null urls passed to the ipfsUrl function
  src/Entities/QueryApi/Ipfs.jsx
Labels: bug

#814 Fix the formatting of the DIG overview page
  src/DIG/OverviewPage.jsx
  src/Posts/RepostButton.jsx
Labels: enhancement

#815 fix: match data format change in QueryApi contract, extra error handling
  src/Entities/QueryApi/DataPlatformIndexerStatuses.jsx
Labels: bug

#817 chore: remove promote from action menu
  src/Posts/Menu.jsx
Labels: enhancement

#821 chore: update idos create account url (1 of 2)
  src/Settings/Identity/Index.jsx
  src/Settings/Identity/Onboarding/Cards.jsx
Labels: ignore-for-release

#820 chore: use `near-social-vm-types` instead of `vm.d.ts` file
  package.json
  vm.d.ts
Labels: dependency

#819 feat: add nearcatalog records to improve search ux
  src/Search/ComponentCard.jsx
  src/Search/FullPage/ComponentCard.jsx
  src/Search/IndexPage.jsx
  src/Search/Insights.jsx
  src/Search/TypeAheadDropdown.jsx
Labels: enhancement
