Repository near/near-discovery-components, pull requests merged in 2024-06, with the labels that each got.

#823 chore: improve `All` tab for search results
  src/Search/TypeAheadDropdown.jsx
Labels: enhancement

#824 chore: improve `All` tab for search results (#823)
  src/Search/TypeAheadDropdown.jsx
Labels: ignore-for-release

#825 fix: search input focus issue
  src/Navigation/Search.jsx
Labels: enhancement

#827 fix: search click event
  src/Navigation/Search.jsx
Labels: ignore-for-release

#831 chore: deploy testnet widgets on mainnet
  src/Gateway/ContactUsPage.jsx
  src/Gateway/Home.jsx
  src/Navigation/NameDropdown.jsx
Labels: allstar

#832 fix: Gateway Homepage
  src/Gateway/Home.jsx
Labels: bug

#833 chore: release testnet widgets on mainnet
  src/Gateway/Home.jsx
Labels: bug

#834 chore: re-add the Resolve an Issue card
  src/Gateway/ContactUsPage.jsx
Labels: enhancement

#836 chore: reduce amount of search categories (Part 1/2)
  src/Navigation/NameDropdown.jsx
  src/Navigation/ProfileDropdown.jsx
  src/Navigation/Search.jsx
  src/Search/ComponentCard.jsx
  src/Search/IndexPage.jsx
  src/Search/TypeAheadDropdown.jsx
Labels: enhancement
